### ISSUE TITLE
Unable to proceed with tutorial 

### ISSUE THREAD

**Issue by jarjarsound** [jpearl01/mcsmrt#1]
Hi, first of all, thank you for your contribution. I have this problem which I was unable to proceed with the tutorial as I was not able to download the correct file. I tried $git clone and download it in .zip format, but the data_stuff.tar.gz was a ACSII TEXT file which contains nth. And I checked the .fasta files in the tutorial were all containing the description only. I haven't try the actual code yet, but I'm just letting you know we have this problem.

**Comment by jpearl01** [comment]
Hi, thanks so much for checking this out, and letting us know about your issue.  It turns out the solution that we used to upload the (relatively) large data files for the tutorial required an additional step on the users part, i.e. to configure git to be able to download them.  Each can still be downloaded individually by clicking on them from the web interface, but only the pointer files come along when getting via `git clone`.  

We've updated the installation instructions to include the requirement of installing git-lfs.  However, in the future we may change where the tutorial data is being stored, however if we do we'll update the project to reflect the new location. Let us know if you still have trouble after installing git-lfs (we are in the process of updating this tutorial to be as user-friendly as possible).

**Comment by jpearl01** [comment]
It turns out that the git lfs solution wasn't a good solution, so we are going to share the tutorial data from google drive, for now.  Link is included in the tutorial!

**Comment by jarjarsound** [comment]
The files problem is resolved, thank you so much, but I have another problem with mcsmrt.rb. It encountered a fatal error after the mapping, the message is as follows:

> usearch -derep_fulllength pre_sequences_for_clustering.fq -fastaout post_dereplicated.fa -sizeout
> 
> ---Fatal error---
> Empty file pre_sequences_for_clustering.fq
> 
> 
> usearch -cluster_otus post_dereplicated.fa -otus post_OTU.fa -uparseout post_uparse.up -relabel OTU_ -sizein -sizeout
> 
> ---Fatal error---
> Cannot open post_dereplicated.fa, errno=2 No such file or directory
> 
> 
> usearch -uchime_ref post_OTU.fa -db /home/cee/mcsmrt_tutorial/rdp_gold.fa -strand plus -nonchimeras post_OTU_nonchimeras.fa -chimeras post_OTU_chimeras.fa -uchimealns post_OTU_alignment.aln -uchimeout post_OTU_uchime_output.txt
> 
> ---Fatal error---
> Cannot open post_OTU.fa, errno=2 No such file or directory
> 
> 
> usearch -usearch_global pre_sequences_for_usearch_global.fq -db post_OTU_nonchimeras.fa -strand plus -id 0.97 -uc post_readmap.uc -otutabout post_OTU_table.txt -notmatched post_unmapped_userach_global.fa -userout post_usearch_glob_results.txt -userfields query+target
> 
> ---Fatal error---
> Empty file pre_sequences_for_usearch_global.fq
> 
> 
> usearch -utax post_OTU_nonchimeras.fa -db /home/cee/mcsmrt_tutorial/16sMicrobial_ncbi_lineage_reference_database.udb -utaxout post_reads.utax -utax_cutoff 0.8 -strand both
> 
> ---Fatal error---
> Empty file post_OTU_nonchimeras.fa
> Traceback (most recent call last):
> 	6: from /home/cee/mcsmrt/get_report.rb:23:in `<main>'
> 	5: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile.rb:123:in `auto'
> 	4: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile.rb:105:in `open'
> 	3: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile.rb:161:in `_open_file'
> 	2: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile/buffer.rb:61:in `open_file'
> 	1: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile/buffer.rb:61:in `open'
> /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile/buffer.rb:61:in `initialize': No such file or directory @ rb_sysopen - post_dereplicated.fa (Errno::ENOENT)
> 
> 
> usearch -ublast post_OTU.fa -db /home/cee/mcsmrt_tutorial/16sMicrobial_ncbi_lineage.fasta -top_hit_only -id 0.9 -blast6out post_OTU_blast.txt -strand both -evalue 0.01 -threads 256 -accel 0.3
> 
> ---Fatal error---
> Cannot open post_OTU.fa, errno=2 No such file or directory
> [DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
> Traceback (most recent call last):
> 	2: from /home/cee/mcsmrt/final_parsing.rb:66:in `<main>'
> 	1: from /home/cee/mcsmrt/final_parsing.rb:66:in `open'
> /home/cee/mcsmrt/final_parsing.rb:66:in `readline': end of file reached (EOFError)
> 00:00 105Mb  100.0% Rows
> 00:00 105Mb Read taxonomy info...done.
> 00:00 106Mb Reading pointers...done.
> 00:00 110Mb Reading db seqs...
> 
> usearch -utax pre_demultiplexed_ccsfilt.fq -db /home/cee/mcsmrt_tutorial/16sMicrobial_ncbi_lineage_reference_database.udb -utaxout all_bc_reads.utax -utax_cutoff 0.8 -strand both -threads 256
> 
> ---Fatal error---
> ReadStdioFile failed, attempted 29731733 bytes, read 25840504 bytes, errno=2
> Traceback (most recent call last):
> 	2: from /home/cee/mcsmrt/merge_all_info_and_utax.rb:4:in `<main>'
> 	1: from /home/cee/mcsmrt/merge_all_info_and_utax.rb:4:in `open'
> /home/cee/mcsmrt/merge_all_info_and_utax.rb:4:in `initialize': No such file or directory @ rb_sysopen - all_bc_reads.utax (Errno::ENOENT)
> Traceback (most recent call last):
> 	6: from /home/cee/mcsmrt/mcsmrt.rb:609:in `<main>'
> 	5: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile.rb:123:in `auto'
> 	4: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile.rb:105:in `open'
> 	3: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile.rb:161:in `_open_file'
> 	2: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile/buffer.rb:61:in `open_file'
> 	1: from /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile/buffer.rb:61:in `open'
> /home/cee/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bio-1.5.2/lib/bio/io/flatfile/buffer.rb:61:in `initialize': No such file or directory @ rb_sysopen - post_dereplicated.fa (Errno::ENOENT) 
> 

So it failed at the pre-clustering, which led to the subsequent failure. Do you have any idea what might cause it? I am still using the tutorial set for trial.For the human genome, I used the whole genome from [NCBI](https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.38), just a piece of info to see if it related to the error. 

Thank you!

**Comment by bhatarchanas** [comment]
Hi, it definitely looks like no reads are passing the filters. Could you please list all the files in the output directory using "ls -la"? The amount of data in each of the files could tell us which filtering step is causing all the reads to be filtered out. My suspicion is that it is the primer matching step where all the reads are getting filtered out. Can you check if you are using the right primers file with the "-p" argument? And see if there is anything in the "pre_primer_map.txt" file. If the issue was primer matching, this file will most likely be empty.
Thanks for getting back to us and really sorry for taking so long to get back to you.

**Comment by jarjarsound** [comment]
Thank you for replying. 

The pre_primer_map.txt looks fine although I have no info regarding what size it would be for a normal situation. ![mcsmrt_failat_presequenceforclustering](https://user-images.githubusercontent.com/38936438/47479220-ea0c4c00-d85e-11e8-9053-5c47d7ca4cfd.png)
As I mentioned, it failed at pre-clustering and that file is empty

The primer I was using is the default 27F and 1492R
> >forward
> AGRGTTYGATYMTGGCTCAG
> >reverse
> RGYTACCTTGTTACGACTT

The distribution I'm using is Ubuntu, would that be one of the factors?

**Comment by bhatarchanas** [comment]
Hi, the file listing with size helps a lot. I just ran through the tutorial myself and had no such issues. I also updated the README a bit. Here are a few follow up questions:
1) Did you run the get_fastqs.rb command/script? 

2) Did the get_fastqs.rb command complete running successfully? This is how the successful completion of that command looks like:
**Sanity check, number of projects are: 1
{"17094"=>["/data/shared/homes/archana/projects/mcsmrt_run_thru_tutorial/mcsmrt_tutorial/data", [#<Barcode_16s_record:0x0000000074fba8 @fow_barcode="0001_Forward", @rev_barcode="0002_Forward", @sample="A_22_gotaq">, #<Barcode_16s_record:0x0000000074f400 @fow_barcode="0003_Forward", @rev_barcode="0004_Forward", @sample="A_hum_22_gotaq">, #<Barcode_16s_record:0x0000000074ef50 @fow_barcode="0005_Forward", @rev_barcode="0006_Forward", @sample="A_22_accu">, #<Barcode_16s_record:0x0000000074ea78 @fow_barcode="0007_Forward", @rev_barcode="0008_Forward", @sample="A_hum_22_accu">]]}
A_22_gotaq;0001_Forward--0002_Forward
A_hum_22_gotaq;0003_Forward--0004_Forward
A_22_accu;0005_Forward--0006_Forward
A_hum_22_accu;0007_Forward--0008_Forward**

3) If get_fastqs.rb ran successfully, can you show me a list of files in the "reads" folder? And also a snapshot of how the sequences in a file looks like will help.

I'm asking for all this because when I ran it, it looks like the size of the files in the reads folder are different from the snapshot you sent. 

Thanks, 
--Archana
